"""Remove grade field from User model

Revision ID: 272816adc414
Revises: 10d3d8f247c4
Create Date: 2025-03-30 13:58:08.512562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272816adc414'
down_revision = '10d3d8f247c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
